// Code generated by thriftgo (0.4.2). DO NOT EDIT.

package status

import (
	"context"
	"fmt"
)

type StatusInfo struct {
	Code int32  `thrift:"Code,1,required" frugal:"1,required,i32" json:"Code"`
	Msg  string `thrift:"Msg,2,required" frugal:"2,required,string" json:"Msg"`
}

func NewStatusInfo() *StatusInfo {
	return &StatusInfo{}
}

func (p *StatusInfo) InitDefault() {
}

func (p *StatusInfo) GetCode() (v int32) {
	return p.Code
}

func (p *StatusInfo) GetMsg() (v string) {
	return p.Msg
}
func (p *StatusInfo) SetCode(val int32) {
	p.Code = val
}
func (p *StatusInfo) SetMsg(val string) {
	p.Msg = val
}

func (p *StatusInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StatusInfo(%+v)", *p)
}

var fieldIDToName_StatusInfo = map[int16]string{
	1: "Code",
	2: "Msg",
}

type StatusService interface {
	Status(ctx context.Context) (r *StatusInfo, err error)
}

type StatusServiceStatusArgs struct {
}

func NewStatusServiceStatusArgs() *StatusServiceStatusArgs {
	return &StatusServiceStatusArgs{}
}

func (p *StatusServiceStatusArgs) InitDefault() {
}

func (p *StatusServiceStatusArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StatusServiceStatusArgs(%+v)", *p)
}

var fieldIDToName_StatusServiceStatusArgs = map[int16]string{}

type StatusServiceStatusResult struct {
	Success *StatusInfo `thrift:"success,0,optional" frugal:"0,optional,StatusInfo" json:"success,omitempty"`
}

func NewStatusServiceStatusResult() *StatusServiceStatusResult {
	return &StatusServiceStatusResult{}
}

func (p *StatusServiceStatusResult) InitDefault() {
}

var StatusServiceStatusResult_Success_DEFAULT *StatusInfo

func (p *StatusServiceStatusResult) GetSuccess() (v *StatusInfo) {
	if !p.IsSetSuccess() {
		return StatusServiceStatusResult_Success_DEFAULT
	}
	return p.Success
}
func (p *StatusServiceStatusResult) SetSuccess(x interface{}) {
	p.Success = x.(*StatusInfo)
}

func (p *StatusServiceStatusResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *StatusServiceStatusResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StatusServiceStatusResult(%+v)", *p)
}

var fieldIDToName_StatusServiceStatusResult = map[int16]string{
	0: "success",
}
