// Code generated by Kitex v0.14.1. DO NOT EDIT.
package statusservice

import (
	server "github.com/cloudwego/kitex/server"
	status "github.com/keainya/status/kitex_gen/status"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler status.StatusService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler status.StatusService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
