// Code generated by Kitex v0.14.1. DO NOT EDIT.

package statusservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	keainya "github.com/keainya/status/kitex_gen/keainya"
	status "github.com/keainya/status/kitex_gen/status"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Status": kitex.NewMethodInfo(
		statusHandler,
		newStatusServiceStatusArgs,
		newStatusServiceStatusResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	statusServiceServiceInfo                = NewServiceInfo()
	statusServiceServiceInfoForClient       = NewServiceInfoForClient()
	statusServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return statusServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return statusServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return statusServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "StatusService"
	handlerType := (*status.StatusService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "status",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.14.1",
		Extra:           extra,
	}
	return svcInfo
}

func statusHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	_ = arg.(*status.StatusServiceStatusArgs)
	realResult := result.(*status.StatusServiceStatusResult)
	success, err := handler.(status.StatusService).Status(ctx)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newStatusServiceStatusArgs() interface{} {
	return status.NewStatusServiceStatusArgs()
}

func newStatusServiceStatusResult() interface{} {
	return status.NewStatusServiceStatusResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Status(ctx context.Context) (r *keainya.BaseResp, err error) {
	var _args status.StatusServiceStatusArgs
	var _result status.StatusServiceStatusResult
	if err = p.c.Call(ctx, "Status", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
