// Code generated by thriftgo (0.4.2). DO NOT EDIT.

package keainya

import (
	"fmt"
)

type BaseResp struct {
	Code int32 `thrift:"Code,1,required" frugal:"1,required,i32" json:"Code"`
}

func NewBaseResp() *BaseResp {
	return &BaseResp{}
}

func (p *BaseResp) InitDefault() {
}

func (p *BaseResp) GetCode() (v int32) {
	return p.Code
}
func (p *BaseResp) SetCode(val int32) {
	p.Code = val
}

func (p *BaseResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BaseResp(%+v)", *p)
}

var fieldIDToName_BaseResp = map[int16]string{
	1: "Code",
}
